##FROM lamtrantuan/easyengine-base-ubuntu:14.04
FROM lamtrantuan/docker-easyengine-wordpress

## ee stack install for mysql and web
RUN ee stack install --web
RUN ee stack install --mysql

COPY ./startStack.sh /

EXPOSE 80 443 22222
